CREATE TABLE IF NOT EXISTS owner
(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  email VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS horse
(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(4095),
  date_of_birth DATE NOT NULL,
  sex ENUM('MALE', 'FEMALE') NOT NULL,
  image BLOB NULL,
  owner_id BIGINT,
  parent1_id BIGINT NULL,
  parent2_id BIGINT NULL,
  CONSTRAINT horse_owner_fk FOREIGN KEY (owner_id) REFERENCES owner(id) ON DELETE SET NULL,
  CONSTRAINT horse_parent1_fk FOREIGN KEY (parent1_id) REFERENCES horse(id) ON DELETE SET NULL,
  CONSTRAINT horse_parent2_fk FOREIGN KEY (parent2_id) REFERENCES horse(id) ON DELETE SET NULL
);



